version: '3'
services:
  address-book-api-prod:
    container_name: address_book_be
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - APP_ENV=production
