apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  namespace: default
type: kubernetes.io/dockercfg
data:
  .dockercfg: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJkcm9wIiwiYXV0aCI6ImRSb3BMVkJ5YjI5ME9tRm5iVjlpYkVSQmVITT0ifX19
