apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: kafka-connect
  name: kafka-connect
spec:
  ports:
    - name: "8084"
      port: 8084
      targetPort: 8083
  selector:
    io.kompose.service: kafka-connect
