apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: keycloak-claim2
  name: keycloak-claim2
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
