apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: redis-exporter
  name: redis-exporter
spec:
  ports:
    - name: "9121"
      port: 9121
      targetPort: 9121
  selector:
    io.kompose.service: redis-exporter
