apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: schema-registry-exporter
  name: schema-registry-exporter
spec:
  ports:
    - name: "5556"
      port: 5556
      targetPort: 5556
  selector:
    io.kompose.service: schema-registry-exporter
